### ISSUE TITLE
No commands registered

### ISSUE THREAD

**Issue by lethefrost** [Daylily-Zeleen/GDScript-Formatter#3] opened 2024-04-05 00:46 UTC
Hi!

I am working on Godot 4.2.1 stable, and I downloaded your formatter plugin from the AssetLib (ver 0.0.4). After enabling it in the Project Settings > Plugins, there's no command as described in the README file showing up in the command palette nor in the menu Project > Tools. Moreover, when trying to disable the plugin, it prints this error message below:

`The Command 'GDScript Formatter/Format GDScript' doesn't exists. Unable to remove it.`

**Comment by Daylily-Zeleen** [comment] 2024-04-05 05:42
Are there any error/warning message when enabling this plugin?

If `gdformat` or `pip` command can't be found when enabling, it should print a warning message,

To eliminate errors as soon as possible, please provide your operating system version and your godot version.

**Comment by Daylily-Zeleen** [comment] 2024-04-05 07:26
> I am not sure why this is showing when enabling the plugin. Shouldn't there be a command or menu item to control the installation/update of that package?

These commands' will be checked when enableing, but not all of them are required:
1. `gdformat` is required for formatting.
2. `pip` is required for installing/updating `gdformat`.

`pip` should install by youself, if you want this plugin to install `pip`, it will required `python` or any other dependency. In orther words, this plugin can't help you to setup enveriment.


> By the way, would it be possible to let the user specify which python/pip environment to use when there are multiple of them in the system? And I am not sure about how it executes the shell commands. I configured the PATH variable in zshrc, but not in bashrc. I'm not sure if that's related or could cause errors when trying to find pip.

Sorry, I'm not familiar with macos.
However, I add two settings to config the actual `gdformat` and `pip` commands, if these command can't be found by default. try to change them (plaese download the latest version from Github).

**Comment by Daylily-Zeleen** [comment] 2024-04-06 06:08
> > Unable to load addon script from path: 'res://addons/gdscript_formatter/gdscript_formatter.gd'. This might be due to a code error in that script.
> > Disabling the addon at 'res://addons/gdscript_formatter/plugin.cfg' to prevent further errors.
> 
> Do you know what's happening?

Sorry, it's my fault. I use a new constants which not exists in Godot 4.2.
Now, I fix it, please download the latest from github page.

**Comment by Daylily-Zeleen** [comment] 2024-04-07 05:58
@lethefrost If the issue is solved, please close this issue.

**Comment by Daylily-Zeleen** [comment] 2024-04-07 07:16
The latest version in AssetLib is waiting for revision.

**Closed** 2024-05-25 06:22 UTC

**Comment by michaelwschultz** [comment] 2024-05-27 09:07
Thanks for the incredible work @Daylily-Zeleen. My favorite addon by far!

I'm having this issue as well on MacOS. Works great on my PC with Windows.

```
-- Begin install gdtoolkit.
-- Install gdtoolkit successfully.
%sGDScript Formatter: The command "gdformat" can't be found in your envrionment.
%s	If have not install "gdtoolkit", install it first.
%s	If had installed "gdtoolkit", change "gdformat_command" to a valid command in "res://addons/gdscript_formatter/format_preference.tres", and save this resource.
```
I'm using pip3 as the pip command due to how MacOS installs pip. Doing this installs gdtoolkit just find and I can verfiy the `gdformat` command works just fine in the terminal. But for some reason, your addon still can't see it.

Path looks good to me. Any other ideas?
```
~/Library/Python/3.9/bin/gdformat 
```

**Comment by Daylily-Zeleen** [comment] 2024-05-27 09:48
@michaelwschultz, please refer to this [comment](https://github.com/Daylily-Zeleen/GDScript-Formatter/issues/5#issuecomment-2131108961).

I have not macOS device and not familiar with macOS. I'm not sure that this steps can help you solve this problem.

**Comment by dillonjason** [comment] 2025-01-15 02:24
For anyone else who comes across this issue.

As described in detail in [this godot issue](https://github.com/godotengine/godot/pull/81266). macOS prevent the user env PATH var from being provided to isolated GUI applications.

The simplest solution is to update the `Gdformat Command` and `Pip Command` config options to be the full path to your bin files.

If you use homebrew and pipx these values by default are:
`Gdformat Command` = `/Users/{your user}/.local/bin/gdformat`
`Pip Command` = `/opt/homebrew/bin/pipx`
